---
AWSTemplateFormatVersion: 2010-09-09
Description: Amazon Aurora DR Automation (Warm Standby)

Parameters:
  Environment:
    Type: String
  Name:
    Type: String
  S3Bucket:
    Type: String
  S3Key:
    Type: String

Resources:
  AuroraDRAutomationRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub '${Environment}-${Name}-role'
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action:
              - 'sts:AssumeRole'
      Path: /
      Policies:
        - PolicyName: !Sub '${Environment}-${Name}-role-policy'
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                Resource: !Sub 'arn:aws:logs:${AWS::Region}:${AWS::AccountId}:*'
              - Effect: Allow
                Action:
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource: !Sub 'arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:/aws/lambda/*'
              - Effect: Allow
                Action:
                  - rds:DescribeGlobalClusters
                  - rds:DescribeDBClusters
                  - rds:FailoverGlobalCluster
                  - rds:SwitchoverGlobalCluster
                Resource: '*'
      Tags:
        - Key: Name
          Value: !Sub '${Environment}-${Name}-role'
        - Key: Environment
          Value: !Ref Environment
  AuroraDRAutomationFunction:
      Type: AWS::Lambda::Function
      Properties:
        FunctionName: !Sub '${Environment}-${Name}-function'
        Runtime: python3.12
        Role:
          Fn::GetAtt:
            - AuroraDRAutomationRole
            - Arn
        Handler: lambda_function.lambda_handler
        Description: Amazon Aurora Disaster Recovery Automation
        Timeout: 600
        MemorySize: 256
        Code:
          S3Bucket: !Ref S3Bucket
          S3Key: !Ref S3Key
        Tags:
          - Key: Name
            Value: !Sub '${Environment}-${Name}-function'
          - Key: Environment
            Value: !Ref Environment

Outputs:
  AuroraDRAutomationRoleARN:
    Value:
      Fn::GetAtt:
        - AuroraDRAutomationRole
        - Arn
  AuroraDRAutomationFunctionName:
    Value: !Ref AuroraDRAutomationFunction